import {cookies} from 'next/headers';
import {redirect} from 'next/navigation';
import {z} from 'zod';
export const ADMIN_COOKIE='it_admin_session';
export class AdminError extends Error {constructor(public status:number,message:string){super(message)}}
export function authConfig(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL?.replace(/\/$/,'');const key=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;if(!url||!key)throw new AdminError(503,'Conecte o Supabase e aplique as migrations para acessar o painel.');return {url,key};}
export async function authRequest(path:string,body?:unknown,token?:string){
 const {url,key}=authConfig();const res=await fetch(`${url}${path}`,{method:body===undefined?'GET':'POST',headers:{apikey:key,'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},body:body===undefined?undefined:JSON.stringify(body),cache:'no-store',signal:AbortSignal.timeout(15000)});const data=await res.json().catch(()=>null);
 if(!res.ok){const status=data?.code==='42501'?403:data?.code==='IT409'?409:data?.code==='IT422'?422:data?.code==='IT404'?404:res.status;throw new AdminError(status,status===409?'O pedido mudou em outra sessão. Recarregue antes de continuar.':status===422?'A ação não é permitida neste estado. Confira os campos e cobranças pendentes.':status===404?'Pedido não encontrado.':status===401||status===403?'Sessão inválida ou conta sem permissão administrativa.':'Não foi possível acessar o serviço. Confira a conexão e as migrations.');}return data;
}
export async function adminRpc(name:string,body:unknown={},token?:string){const access=token??(await cookies()).get(ADMIN_COOKIE)?.value;if(!access)throw new AdminError(401,'Entre no painel para continuar.');return authRequest(`/rest/v1/rpc/${name}`,body,access);}
export async function requireAdmin(){const token=(await cookies()).get(ADMIN_COOKIE)?.value;if(!token)throw new AdminError(401,'Entre no painel para continuar.');const [identity,user]=await Promise.all([adminRpc('impulsetap_admin_identity',{},token),authRequest('/auth/v1/user',undefined,token)]);if(identity.id!==user.id)throw new AdminError(403,'Acesso não autorizado.');return {id:String(user.id),email:String(user.email??''),token};}
export async function adminPage(){try{return await requireAdmin()}catch{redirect('/admin/login')}}
export function sameOrigin(request:Request){const origin=request.headers.get('origin');const expected=process.env.APP_ORIGIN||new URL(request.url).origin;if(!origin||origin!==expected)throw new AdminError(403,'Origem da solicitação inválida.');}
export async function jsonBody(request:Request){const reader=request.body?.getReader();if(!reader)throw new AdminError(400,'Envie os dados.');const chunks:Uint8Array[]=[];let bytes=0;for(;;){const {value,done}=await reader.read();if(done)break;bytes+=value.length;if(bytes>32768){await reader.cancel();throw new AdminError(413,'Solicitação muito grande.');}chunks.push(value);}try{return JSON.parse(Buffer.concat(chunks).toString('utf8'))}catch{throw new AdminError(400,'Dados inválidos.');}}
export function apiFailure(error:unknown){const status=error instanceof AdminError?error.status:error instanceof z.ZodError?422:503;return Response.json({error:error instanceof AdminError?error.message:status===422?'Confira os campos informados.':'Serviço temporariamente indisponível.'},{status,headers:{'Cache-Control':'no-store'}});}
