export const paymentLabels:Record<string,string>={pending:'Aguardando pagamento',paid:'Pago',expired:'Expirado',failed:'Falhou',refunded:'Reembolsado',partially_refunded:'Reembolso parcial'};
export const deliveryLabels:Record<string,string>={awaiting_payment:'Aguardando pagamento',paid:'Pagamento confirmado',awaiting_processing:'Aguardando processamento',processing:'Processando',submitted_to_supplier:'Enviado ao fornecedor',in_progress:'Em andamento',partial:'Entrega parcial',completed:'Concluído',supplier_error:'Erro no fornecedor',cancelled:'Cancelado',refunded:'Reembolsado'};
export interface OrderItem{id:string;network:string;network_name_snapshot:string|null;service_name:string;quantity:number;unit:string;sale_price:number;provider_cost_snapshot:number|null;supplier_service_id_snapshot:string|null;supplier_name_snapshot:string|null;supplier_order_id:string|null;submitted_at:string|null;target:string;links:Array<{url:string;quantity:number}>}
export interface ManagedOrder{id:string;public_id:string;created_at:string;updated_at:string;customer_name:string;customer_email:string;customer_phone:string|null;subtotal:number;discount:number;total:number;gateway_fee:number|null;cost:number|null;gross_profit:number|null;refunded_amount:number;payment_status:string;fulfillment_status:string;version:number;paid_at:string|null;items:OrderItem[]}
export interface OrderDetail extends ManagedOrder {payments:Array<{id:string;provider:string;txid:string|null;status:string;amount:number;created_at:string;paid_at:string|null;expires_at:string|null}>;history:Array<{id:string;event:string;old_status:string|null;new_status:string|null;actor:string|null;created_at:string}>;notes:Array<{id:string;author:string;body:string;created_at:string}>;customer_summary:{orders:number;spent:number;first_order:string}}
export interface DailyMetric {day:string;orders:number;revenue:number;profit:number|null;paid_count:number}
export interface DashboardData {today:DailyMetric;yesterday:DailyMetric;series:DailyMetric[];pending:number;awaiting:number;in_progress:number;problems:number;stalled:number;networks:Array<{network:string;revenue:number}>;notifications:Array<{id:string;title:string;order_id:string|null;created_at:string}>}
export const cash=(value:number|null)=>value===null?'Não apurado':new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(value/100);
export const dateTime=(value:string)=>new Intl.DateTimeFormat('pt-BR',{timeZone:'America/Sao_Paulo',dateStyle:'short',timeStyle:'short'}).format(new Date(value));
export function statusActions(order:ManagedOrder){if(order.payment_status!=='paid')return [];const transitions:Record<string,string[]>={paid:['processing'],awaiting_processing:['processing'],processing:['supplier_error'],submitted_to_supplier:['in_progress','supplier_error'],in_progress:['partial','completed','supplier_error'],partial:['in_progress','completed','supplier_error'],supplier_error:['processing']};return transitions[order.fulfillment_status]??[];}
