-- Bootstrap only: preserves existing admin edits. Run once after migrations.
begin;
insert into impulsetap.social_networks (id,name,description,color,hosts,active) values ('instagram','Instagram','Perfis, posts e Reels','#f447b7','["instagram.com"]'::jsonb,true) on conflict (id) do nothing;
insert into impulsetap.social_networks (id,name,description,color,hosts,active) values ('tiktok','TikTok','Dê espaço aos seus vídeos','#22e7e1','["tiktok.com"]'::jsonb,true) on conflict (id) do nothing;
insert into impulsetap.social_networks (id,name,description,color,hosts,active) values ('youtube','YouTube','Seu canal em movimento','#ff4848','["youtube.com","youtu.be"]'::jsonb,true) on conflict (id) do nothing;
insert into impulsetap.social_networks (id,name,description,color,hosts,active) values ('facebook','Facebook','Páginas e publicações','#308aff','["facebook.com","fb.watch"]'::jsonb,true) on conflict (id) do nothing;
insert into impulsetap.social_networks (id,name,description,color,hosts,active) values ('kwai','Kwai','Vídeos que conectam','#ff9a32','["kwai.com","kw.ai","kuaishou.com"]'::jsonb,true) on conflict (id) do nothing;
insert into impulsetap.social_networks (id,name,description,color,hosts,active) values ('twitter','X / Twitter','Participe da conversa','#e0e7ff','["x.com","twitter.com"]'::jsonb,true) on conflict (id) do nothing;
insert into impulsetap.social_networks (id,name,description,color,hosts,active) values ('telegram','Telegram','Canais e comunidades','#36baff','["t.me","telegram.me"]'::jsonb,true) on conflict (id) do nothing;
insert into impulsetap.social_networks (id,name,description,color,hosts,active) values ('twitch','Twitch','Seu canal em movimento','#9146FF','["twitch.tv","clips.twitch.tv"]'::jsonb,true) on conflict (id) do nothing;
insert into impulsetap.social_networks (id,name,description,color,hosts,active) values ('spotify','Spotify','Música em destaque','#2ddb85','["open.spotify.com","spotify.com"]'::jsonb,false) on conflict (id) do nothing;
insert into impulsetap.social_networks (id,name,description,color,hosts,active) values ('whatsapp','WhatsApp','Canais e atualizações','#38dd93','["whatsapp.com","whatsapp.net"]'::jsonb,true) on conflict (id) do nothing;
insert into impulsetap.social_networks (id,name,description,color,hosts,active) values ('google','Google','Reputação de verdade','#4285f4','["google.com","google.com.br","g.page","maps.app.goo.gl"]'::jsonb,true) on conflict (id) do nothing;
insert into impulsetap.services (id,network,name,category,target_type,multi_link,unit,recurring,description,active,min_quantity,max_quantity,delivery,refill) values ('svc-001','instagram','Seguidores mundiais','Seguidores','profile',false,'seguidores',false,'Informe seu perfil ou canal público. Não precisamos da sua senha.',true,1000,NULL,'','') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-1-1','svc-001',1000,2690,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-1-2','svc-001',5000,12490,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-1-3','svc-001',10000,23990,'') on conflict (id) do nothing;
insert into impulsetap.supplier_services (service_id,supplier_service_id,supplier_cost_per_1000) values ('svc-001',NULL,NULL) on conflict (service_id) do nothing;
insert into impulsetap.services (id,network,name,category,target_type,multi_link,unit,recurring,description,active,min_quantity,max_quantity,delivery,refill) values ('svc-002','instagram','Seguidores brasileiros','Seguidores','profile',false,'seguidores',false,'Informe seu perfil ou canal público. Não precisamos da sua senha.',true,1000,NULL,'','') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-2-1','svc-002',1000,4290,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-2-2','svc-002',5000,19990,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-2-3','svc-002',10000,37990,'') on conflict (id) do nothing;
insert into impulsetap.supplier_services (service_id,supplier_service_id,supplier_cost_per_1000) values ('svc-002',NULL,NULL) on conflict (service_id) do nothing;
insert into impulsetap.services (id,network,name,category,target_type,multi_link,unit,recurring,description,active,min_quantity,max_quantity,delivery,refill) values ('svc-003','instagram','Curtidas mundiais','Curtidas','post',true,'curtidas',false,'Informe o link público do conteúdo que receberá o serviço.',true,1000,NULL,'','') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-3-1','svc-003',1000,449,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-3-2','svc-003',5000,2190,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-3-3','svc-003',10000,3990,'') on conflict (id) do nothing;
insert into impulsetap.supplier_services (service_id,supplier_service_id,supplier_cost_per_1000) values ('svc-003',NULL,NULL) on conflict (service_id) do nothing;
insert into impulsetap.services (id,network,name,category,target_type,multi_link,unit,recurring,description,active,min_quantity,max_quantity,delivery,refill) values ('svc-004','instagram','Curtidas brasileiras','Curtidas','post',true,'curtidas',false,'Informe o link público do conteúdo que receberá o serviço.',true,1000,NULL,'','') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-4-1','svc-004',1000,990,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-4-2','svc-004',5000,4690,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-4-3','svc-004',10000,8990,'') on conflict (id) do nothing;
insert into impulsetap.supplier_services (service_id,supplier_service_id,supplier_cost_per_1000) values ('svc-004',NULL,NULL) on conflict (service_id) do nothing;
insert into impulsetap.services (id,network,name,category,target_type,multi_link,unit,recurring,description,active,min_quantity,max_quantity,delivery,refill) values ('svc-005','instagram','Views de Reels','Visualizações','video',true,'visualizações',false,'Informe o link público do conteúdo que receberá o serviço.',true,1000,NULL,'','') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-5-1','svc-005',1000,190,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-5-2','svc-005',5000,790,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-5-3','svc-005',10000,1490,'') on conflict (id) do nothing;
insert into impulsetap.supplier_services (service_id,supplier_service_id,supplier_cost_per_1000) values ('svc-005',NULL,NULL) on conflict (service_id) do nothing;
insert into impulsetap.services (id,network,name,category,target_type,multi_link,unit,recurring,description,active,min_quantity,max_quantity,delivery,refill) values ('svc-006','instagram','Views de Stories','Stories','post',true,'stories',false,'Informe o link público do conteúdo que receberá o serviço.',true,1000,NULL,'','') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-6-1','svc-006',1000,190,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-6-2','svc-006',5000,790,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-6-3','svc-006',10000,1490,'') on conflict (id) do nothing;
insert into impulsetap.supplier_services (service_id,supplier_service_id,supplier_cost_per_1000) values ('svc-006',NULL,NULL) on conflict (service_id) do nothing;
insert into impulsetap.services (id,network,name,category,target_type,multi_link,unit,recurring,description,active,min_quantity,max_quantity,delivery,refill) values ('svc-007','instagram','Salvos BR','Salvos','post',true,'salvos',false,'Informe o link público do conteúdo que receberá o serviço.',true,1000,NULL,'','') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-7-1','svc-007',1000,290,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-7-2','svc-007',5000,1290,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-7-3','svc-007',10000,2490,'') on conflict (id) do nothing;
insert into impulsetap.supplier_services (service_id,supplier_service_id,supplier_cost_per_1000) values ('svc-007',NULL,NULL) on conflict (service_id) do nothing;
insert into impulsetap.services (id,network,name,category,target_type,multi_link,unit,recurring,description,active,min_quantity,max_quantity,delivery,refill) values ('svc-008','instagram','Compartilhamentos BR','Compartilhamentos','post',true,'compartilhamentos',false,'Informe o link público do conteúdo que receberá o serviço.',true,1000,NULL,'','') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-8-1','svc-008',1000,290,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-8-2','svc-008',5000,1290,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-8-3','svc-008',10000,2490,'') on conflict (id) do nothing;
insert into impulsetap.supplier_services (service_id,supplier_service_id,supplier_cost_per_1000) values ('svc-008',NULL,NULL) on conflict (service_id) do nothing;
insert into impulsetap.services (id,network,name,category,target_type,multi_link,unit,recurring,description,active,min_quantity,max_quantity,delivery,refill) values ('svc-009','tiktok','Seguidores mundiais','Seguidores','profile',false,'seguidores',false,'Informe seu perfil ou canal público. Não precisamos da sua senha.',true,1000,NULL,'','') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-9-1','svc-009',1000,2990,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-9-2','svc-009',5000,13990,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-9-3','svc-009',10000,26990,'') on conflict (id) do nothing;
insert into impulsetap.supplier_services (service_id,supplier_service_id,supplier_cost_per_1000) values ('svc-009',NULL,NULL) on conflict (service_id) do nothing;
insert into impulsetap.services (id,network,name,category,target_type,multi_link,unit,recurring,description,active,min_quantity,max_quantity,delivery,refill) values ('svc-010','tiktok','Seguidores brasileiros','Seguidores','profile',false,'seguidores',false,'Informe seu perfil ou canal público. Não precisamos da sua senha.',true,1000,NULL,'','') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-10-1','svc-010',1000,4990,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-10-2','svc-010',5000,22990,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-10-3','svc-010',10000,43990,'') on conflict (id) do nothing;
insert into impulsetap.supplier_services (service_id,supplier_service_id,supplier_cost_per_1000) values ('svc-010',NULL,NULL) on conflict (service_id) do nothing;
insert into impulsetap.services (id,network,name,category,target_type,multi_link,unit,recurring,description,active,min_quantity,max_quantity,delivery,refill) values ('svc-011','tiktok','Curtidas mundiais','Curtidas','video',true,'curtidas',false,'Informe o link público do conteúdo que receberá o serviço.',true,1000,NULL,'','') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-11-1','svc-011',1000,490,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-11-2','svc-011',5000,2290,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-11-3','svc-011',10000,4290,'') on conflict (id) do nothing;
insert into impulsetap.supplier_services (service_id,supplier_service_id,supplier_cost_per_1000) values ('svc-011',NULL,NULL) on conflict (service_id) do nothing;
insert into impulsetap.services (id,network,name,category,target_type,multi_link,unit,recurring,description,active,min_quantity,max_quantity,delivery,refill) values ('svc-012','tiktok','Curtidas brasileiras','Curtidas','video',true,'curtidas',false,'Informe o link público do conteúdo que receberá o serviço.',true,1000,NULL,'','') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-12-1','svc-012',1000,1190,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-12-2','svc-012',5000,5490,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-12-3','svc-012',10000,9990,'') on conflict (id) do nothing;
insert into impulsetap.supplier_services (service_id,supplier_service_id,supplier_cost_per_1000) values ('svc-012',NULL,NULL) on conflict (service_id) do nothing;
insert into impulsetap.services (id,network,name,category,target_type,multi_link,unit,recurring,description,active,min_quantity,max_quantity,delivery,refill) values ('svc-013','tiktok','Visualizações','Visualizações','video',true,'visualizações',false,'Informe o link público do conteúdo que receberá o serviço.',true,1000,NULL,'','') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-13-1','svc-013',1000,290,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-13-2','svc-013',5000,1190,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-13-3','svc-013',10000,2190,'') on conflict (id) do nothing;
insert into impulsetap.supplier_services (service_id,supplier_service_id,supplier_cost_per_1000) values ('svc-013',NULL,NULL) on conflict (service_id) do nothing;
insert into impulsetap.services (id,network,name,category,target_type,multi_link,unit,recurring,description,active,min_quantity,max_quantity,delivery,refill) values ('svc-014','tiktok','Compartilhamentos','Compartilhamentos','video',true,'compartilhamentos',false,'Informe o link público do conteúdo que receberá o serviço.',true,1000,NULL,'','') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-14-1','svc-014',1000,490,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-14-2','svc-014',5000,2290,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-14-3','svc-014',10000,4290,'') on conflict (id) do nothing;
insert into impulsetap.supplier_services (service_id,supplier_service_id,supplier_cost_per_1000) values ('svc-014',NULL,NULL) on conflict (service_id) do nothing;
insert into impulsetap.services (id,network,name,category,target_type,multi_link,unit,recurring,description,active,min_quantity,max_quantity,delivery,refill) values ('svc-015','tiktok','Salvos/Favoritos','Salvos','video',true,'salvos',false,'Informe o link público do conteúdo que receberá o serviço.',true,1000,NULL,'','') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-15-1','svc-015',1000,490,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-15-2','svc-015',5000,2290,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-15-3','svc-015',10000,4290,'') on conflict (id) do nothing;
insert into impulsetap.supplier_services (service_id,supplier_service_id,supplier_cost_per_1000) values ('svc-015',NULL,NULL) on conflict (service_id) do nothing;
insert into impulsetap.services (id,network,name,category,target_type,multi_link,unit,recurring,description,active,min_quantity,max_quantity,delivery,refill) values ('svc-016','tiktok','Comentários','Comentários','video',false,'comentários',false,'Informe o link público do conteúdo que receberá o serviço.',true,1000,NULL,'','') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-16-1','svc-016',1000,6990,'') on conflict (id) do nothing;
insert into impulsetap.supplier_services (service_id,supplier_service_id,supplier_cost_per_1000) values ('svc-016',NULL,NULL) on conflict (service_id) do nothing;
insert into impulsetap.services (id,network,name,category,target_type,multi_link,unit,recurring,description,active,min_quantity,max_quantity,delivery,refill) values ('svc-017','youtube','Inscritos mundiais','Inscritos','channel',false,'inscritos',false,'Informe seu perfil ou canal público. Não precisamos da sua senha.',false,1000,NULL,'','') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-17-1','svc-017',1000,18990,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-17-2','svc-017',5000,87990,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-17-3','svc-017',10000,169990,'') on conflict (id) do nothing;
insert into impulsetap.supplier_services (service_id,supplier_service_id,supplier_cost_per_1000) values ('svc-017',NULL,NULL) on conflict (service_id) do nothing;
insert into impulsetap.services (id,network,name,category,target_type,multi_link,unit,recurring,description,active,min_quantity,max_quantity,delivery,refill) values ('svc-018','youtube','Inscritos brasileiros','Inscritos','channel',false,'inscritos',false,'Informe seu perfil ou canal público. Não precisamos da sua senha.',false,1000,NULL,'','') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-18-1','svc-018',1000,29990,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-18-2','svc-018',5000,139990,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-18-3','svc-018',10000,269990,'') on conflict (id) do nothing;
insert into impulsetap.supplier_services (service_id,supplier_service_id,supplier_cost_per_1000) values ('svc-018',NULL,NULL) on conflict (service_id) do nothing;
insert into impulsetap.services (id,network,name,category,target_type,multi_link,unit,recurring,description,active,min_quantity,max_quantity,delivery,refill) values ('svc-019','youtube','Visualizações','Visualizações','video',true,'visualizações',false,'Informe o link público do conteúdo que receberá o serviço.',true,1000,NULL,'','') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-19-1','svc-019',1000,1490,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-19-2','svc-019',5000,6490,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-19-3','svc-019',10000,11990,'') on conflict (id) do nothing;
insert into impulsetap.supplier_services (service_id,supplier_service_id,supplier_cost_per_1000) values ('svc-019',NULL,NULL) on conflict (service_id) do nothing;
insert into impulsetap.services (id,network,name,category,target_type,multi_link,unit,recurring,description,active,min_quantity,max_quantity,delivery,refill) values ('svc-020','youtube','Curtidas','Curtidas','video',true,'curtidas',false,'Informe o link público do conteúdo que receberá o serviço.',true,1000,NULL,'','') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-20-1','svc-020',1000,2490,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-20-2','svc-020',5000,11490,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-20-3','svc-020',10000,21990,'') on conflict (id) do nothing;
insert into impulsetap.supplier_services (service_id,supplier_service_id,supplier_cost_per_1000) values ('svc-020',NULL,NULL) on conflict (service_id) do nothing;
insert into impulsetap.services (id,network,name,category,target_type,multi_link,unit,recurring,description,active,min_quantity,max_quantity,delivery,refill) values ('svc-021','youtube','Comentários','Comentários','video',false,'comentários',false,'Informe o link público do conteúdo que receberá o serviço.',false,1000,NULL,'','') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-21-1','svc-021',1000,9990,'') on conflict (id) do nothing;
insert into impulsetap.supplier_services (service_id,supplier_service_id,supplier_cost_per_1000) values ('svc-021',NULL,NULL) on conflict (service_id) do nothing;
insert into impulsetap.services (id,network,name,category,target_type,multi_link,unit,recurring,description,active,min_quantity,max_quantity,delivery,refill) values ('svc-022','youtube','Horas de exibição','Horas de exibição','video',true,'horas',false,'Informe o link público do conteúdo que receberá o serviço.',false,1000,NULL,'','') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-22-1','svc-022',1000,7990,'') on conflict (id) do nothing;
insert into impulsetap.supplier_services (service_id,supplier_service_id,supplier_cost_per_1000) values ('svc-022',NULL,NULL) on conflict (service_id) do nothing;
insert into impulsetap.services (id,network,name,category,target_type,multi_link,unit,recurring,description,active,min_quantity,max_quantity,delivery,refill) values ('svc-023','facebook','Seguidores de página','Seguidores','profile',false,'seguidores',false,'Informe seu perfil ou canal público. Não precisamos da sua senha.',true,1000,NULL,'','') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-23-1','svc-023',1000,3490,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-23-2','svc-023',5000,15990,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-23-3','svc-023',10000,29990,'') on conflict (id) do nothing;
insert into impulsetap.supplier_services (service_id,supplier_service_id,supplier_cost_per_1000) values ('svc-023',NULL,NULL) on conflict (service_id) do nothing;
insert into impulsetap.services (id,network,name,category,target_type,multi_link,unit,recurring,description,active,min_quantity,max_quantity,delivery,refill) values ('svc-024','facebook','Curtidas de página','Curtidas de página','profile',false,'curtidas de página',false,'Informe seu perfil ou canal público. Não precisamos da sua senha.',true,1000,NULL,'','') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-24-1','svc-024',1000,3490,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-24-2','svc-024',5000,15990,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-24-3','svc-024',10000,29990,'') on conflict (id) do nothing;
insert into impulsetap.supplier_services (service_id,supplier_service_id,supplier_cost_per_1000) values ('svc-024',NULL,NULL) on conflict (service_id) do nothing;
insert into impulsetap.services (id,network,name,category,target_type,multi_link,unit,recurring,description,active,min_quantity,max_quantity,delivery,refill) values ('svc-025','facebook','Curtidas em publicação','Curtidas','post',true,'curtidas',false,'Informe o link público do conteúdo que receberá o serviço.',true,1000,NULL,'','') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-25-1','svc-025',1000,790,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-25-2','svc-025',5000,3690,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-25-3','svc-025',10000,6990,'') on conflict (id) do nothing;
insert into impulsetap.supplier_services (service_id,supplier_service_id,supplier_cost_per_1000) values ('svc-025',NULL,NULL) on conflict (service_id) do nothing;
insert into impulsetap.services (id,network,name,category,target_type,multi_link,unit,recurring,description,active,min_quantity,max_quantity,delivery,refill) values ('svc-026','facebook','Reações em publicação','Reações','post',true,'reações',false,'Informe o link público do conteúdo que receberá o serviço.',true,1000,NULL,'','') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-26-1','svc-026',1000,990,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-26-2','svc-026',5000,4490,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-26-3','svc-026',10000,8490,'') on conflict (id) do nothing;
insert into impulsetap.supplier_services (service_id,supplier_service_id,supplier_cost_per_1000) values ('svc-026',NULL,NULL) on conflict (service_id) do nothing;
insert into impulsetap.services (id,network,name,category,target_type,multi_link,unit,recurring,description,active,min_quantity,max_quantity,delivery,refill) values ('svc-027','facebook','Visualizações de vídeo','Visualizações','video',true,'visualizações',false,'Informe o link público do conteúdo que receberá o serviço.',true,1000,NULL,'','') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-27-1','svc-027',1000,490,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-27-2','svc-027',5000,2190,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-27-3','svc-027',10000,3990,'') on conflict (id) do nothing;
insert into impulsetap.supplier_services (service_id,supplier_service_id,supplier_cost_per_1000) values ('svc-027',NULL,NULL) on conflict (service_id) do nothing;
insert into impulsetap.services (id,network,name,category,target_type,multi_link,unit,recurring,description,active,min_quantity,max_quantity,delivery,refill) values ('svc-028','facebook','Compartilhamentos','Compartilhamentos','post',true,'compartilhamentos',false,'Informe o link público do conteúdo que receberá o serviço.',true,1000,NULL,'','') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-28-1','svc-028',1000,790,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-28-2','svc-028',5000,3690,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-28-3','svc-028',10000,6990,'') on conflict (id) do nothing;
insert into impulsetap.supplier_services (service_id,supplier_service_id,supplier_cost_per_1000) values ('svc-028',NULL,NULL) on conflict (service_id) do nothing;
insert into impulsetap.services (id,network,name,category,target_type,multi_link,unit,recurring,description,active,min_quantity,max_quantity,delivery,refill) values ('svc-029','kwai','Seguidores','Seguidores','profile',false,'seguidores',false,'Informe seu perfil ou canal público. Não precisamos da sua senha.',true,1000,NULL,'','') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-29-1','svc-029',1000,2990,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-29-2','svc-029',5000,13990,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-29-3','svc-029',10000,26990,'') on conflict (id) do nothing;
insert into impulsetap.supplier_services (service_id,supplier_service_id,supplier_cost_per_1000) values ('svc-029',NULL,NULL) on conflict (service_id) do nothing;
insert into impulsetap.services (id,network,name,category,target_type,multi_link,unit,recurring,description,active,min_quantity,max_quantity,delivery,refill) values ('svc-030','kwai','Curtidas','Curtidas','video',true,'curtidas',false,'Informe o link público do conteúdo que receberá o serviço.',true,1000,NULL,'','') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-30-1','svc-030',1000,590,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-30-2','svc-030',5000,2790,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-30-3','svc-030',10000,5290,'') on conflict (id) do nothing;
insert into impulsetap.supplier_services (service_id,supplier_service_id,supplier_cost_per_1000) values ('svc-030',NULL,NULL) on conflict (service_id) do nothing;
insert into impulsetap.services (id,network,name,category,target_type,multi_link,unit,recurring,description,active,min_quantity,max_quantity,delivery,refill) values ('svc-031','kwai','Visualizações','Visualizações','video',true,'visualizações',false,'Informe o link público do conteúdo que receberá o serviço.',true,1000,NULL,'','') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-31-1','svc-031',1000,390,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-31-2','svc-031',5000,1690,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-31-3','svc-031',10000,2990,'') on conflict (id) do nothing;
insert into impulsetap.supplier_services (service_id,supplier_service_id,supplier_cost_per_1000) values ('svc-031',NULL,NULL) on conflict (service_id) do nothing;
insert into impulsetap.services (id,network,name,category,target_type,multi_link,unit,recurring,description,active,min_quantity,max_quantity,delivery,refill) values ('svc-032','kwai','Compartilhamentos','Compartilhamentos','video',true,'compartilhamentos',false,'Informe o link público do conteúdo que receberá o serviço.',true,1000,NULL,'','') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-32-1','svc-032',1000,590,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-32-2','svc-032',5000,2790,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-32-3','svc-032',10000,5290,'') on conflict (id) do nothing;
insert into impulsetap.supplier_services (service_id,supplier_service_id,supplier_cost_per_1000) values ('svc-032',NULL,NULL) on conflict (service_id) do nothing;
insert into impulsetap.services (id,network,name,category,target_type,multi_link,unit,recurring,description,active,min_quantity,max_quantity,delivery,refill) values ('svc-033','twitter','Seguidores','Seguidores','profile',false,'seguidores',false,'Informe seu perfil ou canal público. Não precisamos da sua senha.',true,1000,NULL,'','') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-33-1','svc-033',1000,2490,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-33-2','svc-033',5000,11490,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-33-3','svc-033',10000,21990,'') on conflict (id) do nothing;
insert into impulsetap.supplier_services (service_id,supplier_service_id,supplier_cost_per_1000) values ('svc-033',NULL,NULL) on conflict (service_id) do nothing;
insert into impulsetap.services (id,network,name,category,target_type,multi_link,unit,recurring,description,active,min_quantity,max_quantity,delivery,refill) values ('svc-034','twitter','Curtidas','Curtidas','post',true,'curtidas',false,'Informe o link público do conteúdo que receberá o serviço.',true,1000,NULL,'','') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-34-1','svc-034',1000,390,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-34-2','svc-034',5000,1790,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-34-3','svc-034',10000,3290,'') on conflict (id) do nothing;
insert into impulsetap.supplier_services (service_id,supplier_service_id,supplier_cost_per_1000) values ('svc-034',NULL,NULL) on conflict (service_id) do nothing;
insert into impulsetap.services (id,network,name,category,target_type,multi_link,unit,recurring,description,active,min_quantity,max_quantity,delivery,refill) values ('svc-035','twitter','Views','Visualizações','post',true,'visualizações',false,'Informe o link público do conteúdo que receberá o serviço.',true,1000,NULL,'','') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-35-1','svc-035',1000,190,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-35-2','svc-035',5000,790,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-35-3','svc-035',10000,1490,'') on conflict (id) do nothing;
insert into impulsetap.supplier_services (service_id,supplier_service_id,supplier_cost_per_1000) values ('svc-035',NULL,NULL) on conflict (service_id) do nothing;
insert into impulsetap.services (id,network,name,category,target_type,multi_link,unit,recurring,description,active,min_quantity,max_quantity,delivery,refill) values ('svc-036','twitter','Retweets','Compartilhamentos','post',true,'compartilhamentos',false,'Informe o link público do conteúdo que receberá o serviço.',true,1000,NULL,'','') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-36-1','svc-036',1000,990,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-36-2','svc-036',5000,4490,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-36-3','svc-036',10000,8490,'') on conflict (id) do nothing;
insert into impulsetap.supplier_services (service_id,supplier_service_id,supplier_cost_per_1000) values ('svc-036',NULL,NULL) on conflict (service_id) do nothing;
insert into impulsetap.services (id,network,name,category,target_type,multi_link,unit,recurring,description,active,min_quantity,max_quantity,delivery,refill) values ('svc-037','telegram','Membros canal/grupo','Membros','channel',false,'membros',false,'Informe seu perfil ou canal público. Não precisamos da sua senha.',true,1000,NULL,'','') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-37-1','svc-037',1000,1990,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-37-2','svc-037',5000,8990,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-37-3','svc-037',10000,16990,'') on conflict (id) do nothing;
insert into impulsetap.supplier_services (service_id,supplier_service_id,supplier_cost_per_1000) values ('svc-037',NULL,NULL) on conflict (service_id) do nothing;
insert into impulsetap.services (id,network,name,category,target_type,multi_link,unit,recurring,description,active,min_quantity,max_quantity,delivery,refill) values ('svc-038','telegram','Views em post','Visualizações','post',true,'visualizações',false,'Informe o link público do conteúdo que receberá o serviço.',true,1000,NULL,'','') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-38-1','svc-038',1000,290,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-38-2','svc-038',5000,1190,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-38-3','svc-038',10000,2190,'') on conflict (id) do nothing;
insert into impulsetap.supplier_services (service_id,supplier_service_id,supplier_cost_per_1000) values ('svc-038',NULL,NULL) on conflict (service_id) do nothing;
insert into impulsetap.services (id,network,name,category,target_type,multi_link,unit,recurring,description,active,min_quantity,max_quantity,delivery,refill) values ('svc-039','telegram','Reações','Reações','post',true,'reações',false,'Informe o link público do conteúdo que receberá o serviço.',true,1000,NULL,'','') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-39-1','svc-039',1000,590,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-39-2','svc-039',5000,2790,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-39-3','svc-039',10000,5290,'') on conflict (id) do nothing;
insert into impulsetap.supplier_services (service_id,supplier_service_id,supplier_cost_per_1000) values ('svc-039',NULL,NULL) on conflict (service_id) do nothing;
insert into impulsetap.services (id,network,name,category,target_type,multi_link,unit,recurring,description,active,min_quantity,max_quantity,delivery,refill) values ('svc-040','spotify','Streams','Streams','track',true,'streams',false,'Informe o link público do conteúdo que receberá o serviço.',true,1000,NULL,'','') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-40-1','svc-040',1000,1290,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-40-2','svc-040',5000,5790,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-40-3','svc-040',10000,10990,'') on conflict (id) do nothing;
insert into impulsetap.supplier_services (service_id,supplier_service_id,supplier_cost_per_1000) values ('svc-040',NULL,NULL) on conflict (service_id) do nothing;
insert into impulsetap.services (id,network,name,category,target_type,multi_link,unit,recurring,description,active,min_quantity,max_quantity,delivery,refill) values ('svc-041','spotify','Ouvintes mensais','Ouvintes','profile',false,'ouvintes',false,'Informe seu perfil ou canal público. Não precisamos da sua senha.',true,1000,NULL,'','') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-41-1','svc-041',1000,2990,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-41-2','svc-041',5000,13990,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-41-3','svc-041',10000,26990,'') on conflict (id) do nothing;
insert into impulsetap.supplier_services (service_id,supplier_service_id,supplier_cost_per_1000) values ('svc-041',NULL,NULL) on conflict (service_id) do nothing;
insert into impulsetap.services (id,network,name,category,target_type,multi_link,unit,recurring,description,active,min_quantity,max_quantity,delivery,refill) values ('svc-042','spotify','Saves','Salvos','track',true,'salvos',false,'Informe o link público do conteúdo que receberá o serviço.',true,1000,NULL,'','') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-42-1','svc-042',1000,2490,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-42-2','svc-042',5000,11490,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-42-3','svc-042',10000,21990,'') on conflict (id) do nothing;
insert into impulsetap.supplier_services (service_id,supplier_service_id,supplier_cost_per_1000) values ('svc-042',NULL,NULL) on conflict (service_id) do nothing;
insert into impulsetap.services (id,network,name,category,target_type,multi_link,unit,recurring,description,active,min_quantity,max_quantity,delivery,refill) values ('svc-043','spotify','Seguidores de perfil','Seguidores','profile',false,'seguidores',false,'Informe seu perfil ou canal público. Não precisamos da sua senha.',true,1000,NULL,'','') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-43-1','svc-043',1000,3490,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-43-2','svc-043',5000,15990,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-43-3','svc-043',10000,29990,'') on conflict (id) do nothing;
insert into impulsetap.supplier_services (service_id,supplier_service_id,supplier_cost_per_1000) values ('svc-043',NULL,NULL) on conflict (service_id) do nothing;
insert into impulsetap.services (id,network,name,category,target_type,multi_link,unit,recurring,description,active,min_quantity,max_quantity,delivery,refill) values ('svc-044','spotify','Inclusão em playlist','Playlist','track',false,'música',false,'Informe o link público do conteúdo que receberá o serviço.',true,1,NULL,'','') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-44-1','svc-044',1,3990,'') on conflict (id) do nothing;
insert into impulsetap.supplier_services (service_id,supplier_service_id,supplier_cost_per_1000) values ('svc-044',NULL,NULL) on conflict (service_id) do nothing;
insert into impulsetap.services (id,network,name,category,target_type,multi_link,unit,recurring,description,active,min_quantity,max_quantity,delivery,refill) values ('svc-045','whatsapp','Seguidores de canal','Seguidores','channel',false,'seguidores',false,'Informe seu perfil ou canal público. Não precisamos da sua senha.',true,1000,NULL,'','') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-45-1','svc-045',1000,3990,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-45-2','svc-045',5000,18490,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-45-3','svc-045',10000,34990,'') on conflict (id) do nothing;
insert into impulsetap.supplier_services (service_id,supplier_service_id,supplier_cost_per_1000) values ('svc-045',NULL,NULL) on conflict (service_id) do nothing;
insert into impulsetap.services (id,network,name,category,target_type,multi_link,unit,recurring,description,active,min_quantity,max_quantity,delivery,refill) values ('svc-046','whatsapp','Views de canal/status','Visualizações','post',true,'visualizações',false,'Informe o link público do conteúdo que receberá o serviço.',true,1000,NULL,'','') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-46-1','svc-046',1000,990,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-46-2','svc-046',5000,4490,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-46-3','svc-046',10000,8490,'') on conflict (id) do nothing;
insert into impulsetap.supplier_services (service_id,supplier_service_id,supplier_cost_per_1000) values ('svc-046',NULL,NULL) on conflict (service_id) do nothing;
insert into impulsetap.services (id,network,name,category,target_type,multi_link,unit,recurring,description,active,min_quantity,max_quantity,delivery,refill) values ('svc-047','whatsapp','Reações de canal','Reações','post',true,'reações',false,'Informe o link público do conteúdo que receberá o serviço.',true,1000,NULL,'','') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-47-1','svc-047',1000,1490,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-47-2','svc-047',5000,6990,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-47-3','svc-047',10000,12990,'') on conflict (id) do nothing;
insert into impulsetap.supplier_services (service_id,supplier_service_id,supplier_cost_per_1000) values ('svc-047',NULL,NULL) on conflict (service_id) do nothing;
insert into impulsetap.services (id,network,name,category,target_type,multi_link,unit,recurring,description,active,min_quantity,max_quantity,delivery,refill) values ('svc-048','google','Criação/otimização do Perfil da Empresa','Perfil da Empresa','business',false,'serviço',false,'Serviço de gestão para o seu negócio, com avaliações autênticas.',true,1,NULL,'','') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-48-1','svc-048',1,14990,'') on conflict (id) do nothing;
insert into impulsetap.supplier_services (service_id,supplier_service_id,supplier_cost_per_1000) values ('svc-048',NULL,NULL) on conflict (service_id) do nothing;
insert into impulsetap.services (id,network,name,category,target_type,multi_link,unit,recurring,description,active,min_quantity,max_quantity,delivery,refill) values ('svc-049','google','QR Code + página para avaliações reais','Avaliações reais','business',false,'serviço',false,'Serviço de gestão para o seu negócio, com avaliações autênticas.',true,1,NULL,'','') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-49-1','svc-049',1,4990,'') on conflict (id) do nothing;
insert into impulsetap.supplier_services (service_id,supplier_service_id,supplier_cost_per_1000) values ('svc-049',NULL,NULL) on conflict (service_id) do nothing;
insert into impulsetap.services (id,network,name,category,target_type,multi_link,unit,recurring,description,active,min_quantity,max_quantity,delivery,refill) values ('svc-050','google','Respostas para até 20 avaliações','Respostas','business',false,'mês',true,'Serviço de gestão para o seu negócio, com avaliações autênticas.',true,1,NULL,'','') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-50-1','svc-050',1,9990,'') on conflict (id) do nothing;
insert into impulsetap.supplier_services (service_id,supplier_service_id,supplier_cost_per_1000) values ('svc-050',NULL,NULL) on conflict (service_id) do nothing;
insert into impulsetap.services (id,network,name,category,target_type,multi_link,unit,recurring,description,active,min_quantity,max_quantity,delivery,refill) values ('svc-051','google','Gestão mensal completa','Gestão','business',false,'mês',true,'Serviço de gestão para o seu negócio, com avaliações autênticas.',true,1,NULL,'','') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-51-1','svc-051',1,24990,'') on conflict (id) do nothing;
insert into impulsetap.supplier_services (service_id,supplier_service_id,supplier_cost_per_1000) values ('svc-051',NULL,NULL) on conflict (service_id) do nothing;
insert into impulsetap.services (id,network,name,category,target_type,multi_link,unit,recurring,description,active,min_quantity,max_quantity,delivery,refill) values ('svc-052','youtube','Visualizações de Shorts','Shorts','video',true,'visualizações',false,'Informe o link público do vídeo.',true,1000,NULL,'','') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-52-1','svc-052',1000,1490,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-52-2','svc-052',5000,6490,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-52-3','svc-052',10000,11990,'') on conflict (id) do nothing;
insert into impulsetap.supplier_services (service_id,supplier_service_id,supplier_cost_per_1000) values ('svc-052',NULL,NULL) on conflict (service_id) do nothing;
insert into impulsetap.services (id,network,name,category,target_type,multi_link,unit,recurring,description,active,min_quantity,max_quantity,delivery,refill) values ('svc-053','twitch','Seguidores Twitch','Seguidores','profile',false,'seguidores',false,'Informe o link público do canal. Nunca solicitamos sua senha.',true,1000,30000,'','30 dias') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-53-1','svc-053',1000,990,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-53-2','svc-053',5000,3990,'MAIS ESCOLHIDO') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-53-3','svc-053',10000,6990,'') on conflict (id) do nothing;
insert into impulsetap.supplier_services (service_id,supplier_service_id,supplier_cost_per_1000) values ('svc-053','110',1.42) on conflict (service_id) do nothing;
insert into impulsetap.services (id,network,name,category,target_type,multi_link,unit,recurring,description,active,min_quantity,max_quantity,delivery,refill) values ('svc-054','twitch','Visualizações em vídeos Twitch','Visualizações','video',true,'visualizações',false,'Informe o link público do vídeo.',true,1000,NULL,'','') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-54-1','svc-054',1000,2490,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-54-2','svc-054',5000,10990,'') on conflict (id) do nothing;
insert into impulsetap.service_packages (id,service_id,quantity,price,badge) values ('pkg-54-3','svc-054',10000,19990,'') on conflict (id) do nothing;
insert into impulsetap.supplier_services (service_id,supplier_service_id,supplier_cost_per_1000) values ('svc-054','934',8.99) on conflict (service_id) do nothing;
insert into impulsetap.services (id,network,name,category,target_type,multi_link,unit,recurring,description,active,min_quantity,max_quantity,delivery,refill) values ('svc-055','twitch','Espectadores ao vivo','Espectadores ao vivo','channel',false,'espectadores',false,'Informe o link público do canal. Nunca solicitamos sua senha.',false,NULL,NULL,'','') on conflict (id) do nothing;
insert into impulsetap.supplier_services (service_id,supplier_service_id,supplier_cost_per_1000) values ('svc-055',NULL,NULL) on conflict (service_id) do nothing;
insert into impulsetap.services (id,network,name,category,target_type,multi_link,unit,recurring,description,active,min_quantity,max_quantity,delivery,refill) values ('svc-056','twitch','Viewers simultâneos','Viewers simultâneos','channel',false,'viewers',false,'Informe o link público do canal. Nunca solicitamos sua senha.',false,NULL,NULL,'','') on conflict (id) do nothing;
insert into impulsetap.supplier_services (service_id,supplier_service_id,supplier_cost_per_1000) values ('svc-056',NULL,NULL) on conflict (service_id) do nothing;
insert into impulsetap.services (id,network,name,category,target_type,multi_link,unit,recurring,description,active,min_quantity,max_quantity,delivery,refill) values ('svc-057','twitch','Visualizações de live','Visualizações de live','channel',false,'visualizações',false,'Informe o link público do canal. Nunca solicitamos sua senha.',false,NULL,NULL,'','') on conflict (id) do nothing;
insert into impulsetap.supplier_services (service_id,supplier_service_id,supplier_cost_per_1000) values ('svc-057',NULL,NULL) on conflict (service_id) do nothing;
insert into impulsetap.order_bumps (id,main_service_ids,service_id,package_id,price) values ('ig-likes','["svc-001","svc-002"]'::jsonb,'svc-004','pkg-4-1',790) on conflict (id) do nothing;
commit;
