import Link from 'next/link';
import {adminPage,adminRpc} from '@/lib/admin-server';
import {paymentLabels,deliveryLabels,type ManagedOrder} from '@/lib/operations';
import {OrdersTable} from '@/components/admin-orders';
export default async function Page({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
 const admin=await adminPage();const p=await searchParams;const filter:Record<string,string|number>={page:Math.max(1,Math.min(100000,Math.floor(Number(p.page)||1)))};
 for(const key of ['q','payment','delivery','network','service','supplier'])if(p[key])filter[key]=p[key]!.slice(0,200);
 if(p.from&&/^\d{4}-\d{2}-\d{2}$/.test(p.from)&&!Number.isNaN(Date.parse(p.from)))filter.from=p.from+'T00:00:00-03:00';
 if(p.to&&/^\d{4}-\d{2}-\d{2}$/.test(p.to)&&!Number.isNaN(Date.parse(p.to)))filter.to=new Date(new Date(p.to+'T00:00:00-03:00').getTime()+86400000).toISOString();
 const data:{rows:ManagedOrder[];total:number;page:number}=await adminRpc('impulsetap_admin_orders',{p_filter:filter},admin.token);
 const pageLink=(page:number)=>{const params=new URLSearchParams();for(const [k,v] of Object.entries(p))if(v)params.set(k,v);params.set('page',String(page));return '/admin/pedidos?'+params.toString()};
 return <><div className="ops-title"><div><h1>Pedidos</h1><p>{data.total} pedido(s) encontrado(s). Acompanhe da compra à entrega.</p></div></div><form className="ops-filter ops-panel"><label>Buscar<input name="q" defaultValue={p.q} placeholder="Código, nome, e-mail ou WhatsApp"/></label><label>Pagamento<select name="payment" defaultValue={p.payment}><option value="">Todos</option>{Object.entries(paymentLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Entrega<select name="delivery" defaultValue={p.delivery}><option value="">Todas</option>{Object.entries(deliveryLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Rede<input name="network" defaultValue={p.network} placeholder="instagram, twitch…"/></label><label>Serviço<input name="service" defaultValue={p.service}/></label><label>Fornecedor<input name="supplier" defaultValue={p.supplier}/></label><label>De<input name="from" type="date" defaultValue={p.from}/></label><label>Até<input name="to" type="date" defaultValue={p.to}/></label><button className="button primary">Filtrar</button><Link href="/admin/pedidos" className="button secondary">Limpar</Link></form><section className="ops-panel"><OrdersTable orders={data.rows}/><div className="ops-pagination">{data.page>1?<Link className="button secondary" href={pageLink(data.page-1)}>Anterior</Link>:<span/>}<span>Página {data.page} de {Math.max(1,Math.ceil(data.total/25))}</span>{data.page*25<data.total?<Link className="button secondary" href={pageLink(data.page+1)}>Próxima</Link>:<span/>}</div></section></>
}
