'use client';
import {useState} from 'react';
import Link from 'next/link';
import {X,CheckCircle2} from 'lucide-react';
import {money} from '@/lib/catalog';
import type {CartItem} from '@/lib/cart';
import {customerSchema} from '@/lib/validation';
export function CartCheckout({items,onClose,onDone}:{items:CartItem[];onClose:()=>void;onDone:()=>void}){
 const [customer,setCustomer]=useState({name:'',email:'',phone:'',terms:false});const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [result,setResult]=useState<{public_id:string;total:number}|null>(null);const total=items.reduce((sum,item)=>sum+item.price,0);
 async function submit(e:React.FormEvent){e.preventDefault();const parsed=customerSchema.safeParse(customer);if(!parsed.success){setError(parsed.error.issues[0]?.message||'Confira seus dados.');return}setBusy(true);setError('');const payload={request_key:crypto.randomUUID(),customer,items:items.map(item=>({service_id:item.serviceId,quantity:item.quantity,links:[{url:item.target,quantity:item.quantity}]}))};try{if(process.env.NEXT_PUBLIC_DEMO_MODE==='true'){setResult({public_id:`DEMO-${Date.now()}`,total});onDone();return}const response=await fetch('/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok)throw new Error(data.error);setResult(data);onDone()}catch(e){setError(e instanceof Error?e.message:'Não foi possível criar o pedido.')}finally{setBusy(false)}}
 return <div className="tutorial-backdrop"><section className="cart-checkout" role="dialog" aria-modal="true"><button className="icon-button tutorial-close" onClick={onClose} aria-label="Fechar"><X/></button>{result?<div className="success-state"><CheckCircle2 size={52}/><h2>Pedido registrado</h2><p>{result.public_id}</p><strong>{money(result.total)}</strong><p className="notice">Uma única cobrança PIX será associada aos {items.length} itens após a homologação do gateway.</p><Link className="button primary full" href={`/pedido/${result.public_id}`}>Acompanhar pedido</Link></div>:<><h2>Finalizar pedido</h2><p className="muted">Uma única cobrança para todos os itens.</p><div className="cart-checkout-total"><span>{items.length} itens</span><strong>{money(total)}</strong></div><form onSubmit={submit}><label>Nome<input value={customer.name} onChange={e=>setCustomer({...customer,name:e.target.value})} required/></label><label>E-mail<input type="email" value={customer.email} onChange={e=>setCustomer({...customer,email:e.target.value})} required/></label><label>WhatsApp<input value={customer.phone} onChange={e=>setCustomer({...customer,phone:e.target.value})}/></label><label className="checkbox-line"><input type="checkbox" checked={customer.terms} onChange={e=>setCustomer({...customer,terms:e.target.checked})}/><span>Aceito os termos.</span></label>{error&&<p className="error">{error}</p>}<button className="button primary full" disabled={busy}>{busy?'Criando…':'Criar pedido'}</button></form></>}</section></div>
}
