'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {Check,CheckCircle2,ChevronLeft,LockKeyhole,Plus,ShieldCheck,X,ReceiptText} from 'lucide-react';
import {motion,AnimatePresence,useReducedMotion} from 'framer-motion';
import {type Service,type Package,money,number,getNetwork,type Catalog} from '@/lib/catalog';
import {customerSchema,validateTarget,type TargetLink} from '@/lib/validation';
import {createDemoId,saveOrder,type DemoOrder} from '@/lib/demo-orders';
import {NetworkIcon} from './brand';
import {settings} from '@/lib/settings';
export function Checkout({catalog,service,pkg,links,onClose}:{catalog:Catalog;service:Service;pkg:Package;links:TargetLink[];onClose:()=>void}){
const {orderBumps,services}=catalog;
const ref=useRef<HTMLDialogElement>(null);const reduced=useReducedMotion();
const[realOrder,setRealOrder]=useState<{public_id:string;total:number}|null>(null);const requestKey=useRef('');
const[step,setStep]=useState(0);const[customer,setCustomer]=useState({name:'',email:'',phone:'',terms:false});const[error,setError]=useState('');const[busy,setBusy]=useState(false);const[added,setAdded]=useState(false);const[bumpTarget,setBumpTarget]=useState('');const[order,setOrder]=useState<DemoOrder|null>(null);
const bump=settings.enableOrderBumps?orderBumps.find(b=>b.mainServiceIds.includes(service.id)):undefined;const bumpService=services.find(s=>s.id===bump?.serviceId);const total=pkg.price+(added&&bump?bump.price:0);
useEffect(()=>{const d=ref.current;d?.showModal();const overflow=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=overflow;d?.close()}},[]);
function next(){setError('');if(step===0){const parsed=customerSchema.safeParse(customer);if(!parsed.success){setError(parsed.error.issues[0].message);return;}setStep(1);}else if(step===1){if(added&&bumpService){const err=validateTarget(bumpTarget,bumpService);if(err){setError(err);return;}}setStep(2);}}
async function createOrder(){if(!settings.demoMode){setBusy(true);setError('');if(!requestKey.current)requestKey.current=crypto.randomUUID();try{const items=[{package_id:pkg.id,links},...(added&&bump&&bumpService?[{package_id:bump.packageId,bump_id:bump.id,links:[{url:bumpTarget,quantity:bumpService.packages.find(p=>p.id===bump.packageId)!.quantity}]}]:[])];const res=await fetch('/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({request_key:requestKey.current,customer,items})});const result=await res.json();if(!res.ok)throw new Error(result.error);setRealOrder(result);setStep(3);}catch(e){setError(e instanceof Error?e.message:'Não foi possível criar o pedido.')}finally{setBusy(false)}return;}setBusy(true);setError('');try{const item:DemoOrder={id:createDemoId(),createdAt:new Date().toISOString(),serviceId:service.id,serviceName:service.name,network:service.network,quantity:pkg.quantity,total,target:links.map(l=>`${l.url} (${number(l.quantity)})`).join(' · '),status:'pending',demo:true,...(added&&bump&&bumpService?{additional:{name:bumpService.name,target:bumpTarget,price:bump.price}}:{})};saveOrder(item);setOrder(item);setStep(3);}catch{setError('Não foi possível salvar a demonstração neste navegador. Permita o armazenamento da sessão e tente novamente.');}finally{setBusy(false);}}
function confirm(){if(!order||!settings.demoMode)return;try{const updated={...order,status:'confirmed' as const};saveOrder(updated);setOrder(updated);setStep(4);}catch{setError('Não foi possível atualizar seu pedido de demonstração.');}}
return <dialog ref={ref} aria-label="Checkout ImpulseTap" className="checkout-dialog" onCancel={onClose}><div className="dialog-top"><span><LockKeyhole size={16}/>Checkout ImpulseTap</span><button className="icon-button" onClick={onClose} aria-label="Fechar checkout"><X/></button></div>{settings.demoMode&&<div className="dialog-demo">Demonstração · Sem cobrança e sem entrega real</div>}{step<3&&<ol className="checkout-steps">{['Seus dados','Revisão','Pagamento'].map((s,i)=><li key={s} className={i===step?'active':i<step?'done':''} aria-current={i===step?'step':undefined}><span>{i<step?<Check size={14}/>:i+1}</span>{s}</li>)}</ol>}<AnimatePresence mode="wait"><motion.div key={step} initial={reduced?false:{opacity:0,x:12}} animate={{opacity:1,x:0}} transition={{duration:.18}} className="dialog-body">
{step===0&&<><h2>Vamos identificar seu pedido.</h2><p className="muted">Confira seus dados para continuar.</p><form onSubmit={e=>{e.preventDefault();next()}}><label>Nome<input autoComplete="name" value={customer.name} onChange={e=>setCustomer({...customer,name:e.target.value})} placeholder="Seu nome" maxLength={100}/></label><label>E-mail<input type="email" autoComplete="email" value={customer.email} onChange={e=>setCustomer({...customer,email:e.target.value})} placeholder="voce@email.com" maxLength={254}/></label><label>WhatsApp <span className="optional">opcional</span><input type="tel" autoComplete="tel" value={customer.phone} onChange={e=>setCustomer({...customer,phone:e.target.value})} placeholder="(21) 99999-9999" maxLength={20}/></label><label className="checkbox-line"><input type="checkbox" checked={customer.terms} onChange={e=>setCustomer({...customer,terms:e.target.checked})}/><span>Li os <Link href="/termos" target="_blank">termos</Link> e a <Link href="/privacidade" target="_blank">privacidade</Link>.</span></label><p className="caption">{settings.demoMode?'Seus dados pessoais não são enviados nesta demonstração.':'Usaremos estes dados para identificar e acompanhar seu pedido.'}</p>{error&&<p role="alert" className="error">{error}</p>}<button type="submit" className="button primary full">Continuar</button></form></>}
{step===1&&<><h2>Do seu jeito. Sem surpresas.</h2><p className="muted">Revise o serviço e o destino do pedido.</p><div className="review-card"><NetworkIcon id={service.network}/><div><strong>{service.name}</strong><span>{getNetwork(service.network).name} · {number(pkg.quantity)} {service.unit}</span></div><b>{money(pkg.price)}</b></div><div className="target-review">{links.map((l,i)=><div key={i}><span>{l.url}</span><strong>{number(l.quantity)}</strong></div>)}</div>{bump&&bumpService&&<div className={`bump-card ${added?'selected':''}`}><span className="bump-title"><Plus size={17}/>Complete seu pedido</span><h3>+ 1.000 curtidas brasileiras</h3><p>Para uma publicação do seu Instagram.</p><div className="bump-price"><s>{money(bumpService.packages[0].price)}</s><strong>{money(bump.price)}</strong><label className="checkbox-line"><input type="checkbox" checked={added} onChange={e=>setAdded(e.target.checked)}/>Adicionar</label></div>{added&&<label>Link da publicação<input value={bumpTarget} onChange={e=>setBumpTarget(e.target.value)} placeholder="https://www.instagram.com/p/..."/></label>}</div>}<p className="notice"><ShieldCheck size={17}/>Prazos e regras de reposição serão definidos por serviço antes da abertura das vendas.</p><div className="total-row"><span>Total{service.recurring?' mensal':''}</span><b>{money(total)}</b></div>{error&&<p className="error" role="alert">{error}</p>}<button className="button primary full" onClick={next}>{settings.demoMode?'Ir para pagamento demonstrativo':'Revisar e confirmar pedido'}</button><button className="back-button" onClick={()=>setStep(0)}><ChevronLeft size={16}/>Voltar aos dados</button></>}
{step===2&&<><div className="payment-icon"><ReceiptText size={34}/></div><h2>{settings.demoMode?'Experimente o fluxo completo.':'Confirme seu pedido.'}</h2><p className="muted">{settings.demoMode?'Nenhum PIX será gerado. Vamos criar um pedido de exemplo.':'O pedido será registrado com o preço confirmado no servidor. O PIX está em homologação; nenhuma cobrança será feita nesta etapa.'}</p><div className="payment-total"><span>{settings.demoMode?'Valor demonstrativo':'Valor a confirmar no servidor'}</span><strong>{money(total)}{service.recurring&&<small>/mês</small>}</strong></div><p className="notice">Não faça transferências. Pagamento e entrega reais ainda não estão disponíveis.</p>{error&&<p className="error" role="alert">{error}</p>}<button className="button primary full" disabled={busy} onClick={createOrder}>{busy?'Criando…':settings.demoMode?'Criar pedido de demonstração':'Registrar pedido pendente'}</button><button className="back-button" onClick={()=>setStep(1)}><ChevronLeft size={16}/>Revisar pedido</button></>}
{step===3&&realOrder&&<><h2>Pedido registrado.</h2><p>{realOrder.public_id}</p><div className="payment-total"><span>Total confirmado no banco</span><strong>{money(realOrder.total)}</strong></div><p className="notice">Pagamento pendente. O PIX ainda está em homologação. Não faça transferências nem envie comprovantes.</p><Link href={`/pedido/${realOrder.public_id}`} className="button primary full">Acompanhar pedido</Link></>}
{step===3&&order&&<><div className="payment-icon"><ReceiptText size={34}/></div><h2>Pedido de exemplo criado.</h2><p className="muted">{order.id}</p><div className="payment-total"><span>Aguardando confirmação simulada</span><strong>{money(total)}</strong></div><p className="notice">Em produção, esta etapa exibirá o PIX e aguardará a confirmação do gateway.</p>{error&&<p className="error" role="alert">{error}</p>}<button className="button primary full" onClick={confirm}>Simular confirmação do pagamento</button><Link href={`/pedidos?codigo=${order.id}`} className="back-button">Acompanhar sem confirmar</Link></>}
{step===4&&order&&<div className="success-state"><CheckCircle2 size={58}/><h2>Simulação concluída!</h2><p>Você percorreu o fluxo de compra da ImpulseTap. Nenhum valor foi cobrado.</p><div className="receipt-code">{order.id}</div><div className="review-card"><NetworkIcon id={service.network}/><div><strong>{service.name}</strong><span>{number(pkg.quantity)} {service.unit}</span></div></div><Link className="button primary full" href={`/pedidos?codigo=${order.id}`}>Acompanhar demonstração</Link><button className="back-button" onClick={onClose}>Continuar explorando</button></div>}
</motion.div></AnimatePresence></dialog>
}
