'use client';
import {useState} from 'react';
import Link from 'next/link';
import {Menu,X,ShieldCheck,LockKeyhole,PackageCheck,MessageCircle,ShoppingBag,ReceiptText} from 'lucide-react';
import {Logo} from './brand';
import {settings} from '@/lib/settings';
export function Header(){const[open,setOpen]=useState(false);return <><div className="demo-banner">{settings.demoMode?'Modo demonstração · Explore os serviços. Nenhuma cobrança será realizada.':'Vendas ainda indisponíveis · Estamos preparando a abertura.'}</div><header className="header"><div className="container header-inner"><Link href="/" aria-label="ImpulseTap início"><Logo/></Link><nav aria-label="Navegação principal" className={open?'nav open':'nav'}>{[['Início','/'],['Serviços','/#servicos'],['Como funciona','/#como-funciona'],['Meus pedidos','/pedidos'],['Dúvidas','/#duvidas']].map(([label,href])=><Link onClick={()=>setOpen(false)} key={href} href={href}>{label}</Link>)}</nav><Link href="/#servicos" className="button primary header-buy">Comprar agora</Link><button type="button" className="icon-button mobile-menu" aria-label={open?'Fechar menu':'Abrir menu'} aria-expanded={open} onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div></header></>}
export function TrustBar(){return <div className="trust-bar">{[[LockKeyhole,'Não pedimos sua senha'],[ShieldCheck,'Processo simples'],[PackageCheck,'Acompanhe seu pedido']].map(([Icon,label])=>{const I=Icon as typeof LockKeyhole;return <span key={String(label)}><I size={17}/>{String(label)}</span>})}</div>}
export function Support(){const[open,setOpen]=useState(false);return <><button className="whatsapp-float" aria-label="Precisa de ajuda? Suporte" onClick={()=>{if(settings.whatsapp){window.open(`https://wa.me/${settings.whatsapp}?text=${encodeURIComponent('Olá! Vim pelo site da ImpulseTap e preciso de ajuda.')}`,'_blank','noopener,noreferrer')}else setOpen(!open)}}><MessageCircle size={24}/><span>Precisa de ajuda?<strong>Fale com a gente</strong></span></button>{open&&<div className="support-popover" role="status"><button className="icon-button" aria-label="Fechar suporte" onClick={()=>setOpen(false)}><X size={18}/></button><strong>Suporte em preparação</strong><p>O WhatsApp oficial será disponibilizado antes da abertura das vendas.</p><Link href="/#duvidas" onClick={()=>setOpen(false)}>Consultar dúvidas frequentes</Link></div>}<nav className="mobile-bottom" aria-label="Acesso rápido"><Link href="/#servicos"><ShoppingBag size={19}/>Comprar</Link><Link href="/pedidos"><ReceiptText size={19}/>Pedidos</Link><button onClick={()=>setOpen(!open)}><MessageCircle size={19}/>Suporte</button></nav></>}
export function Footer(){return <footer className="footer"><div className="container footer-grid"><div><Link href="/"><Logo/></Link><p>Seu próximo passo nas redes<br/>começa com um toque.</p></div><div><strong>Explore</strong><Link href="/#servicos">Serviços</Link><Link href="/pedidos">Meus pedidos</Link><Link href="/#como-funciona">Como funciona</Link></div><div><strong>Informações</strong><Link href="/termos">Termos de uso</Link><Link href="/privacidade">Privacidade</Link><Link href="/politica-de-reembolso">Reembolsos</Link><Link href="/admin">Administração</Link></div><div className="footer-note"><ShieldCheck size={24}/><p>A ImpulseTap não é afiliada oficialmente às plataformas listadas. As marcas pertencem a seus respectivos proprietários.</p></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} ImpulseTap</span><span>Feito para simplificar.</span></div></footer>}
