'use client';
import {useEffect,useState} from 'react';
import {ChevronLeft,ChevronRight,X,CheckCircle2} from 'lucide-react';
const steps=[['network','Escolha sua rede social','Instagram, TikTok, YouTube, Facebook, Kwai, X, Telegram, WhatsApp ou Twitch.'],['service','Escolha o serviço','Seguidores, curtidas, visualizações, compartilhamentos e outros serviços ativos.'],['variant','Escolha a variação','Compare opções mundiais, brasileiras ou outras configurações disponíveis.'],['link','Cole o link correto','Perfil para seguidores; publicação para curtidas; vídeo ou Reel para visualizações. Nunca sua senha.'],['quantity','Escolha a quantidade','Digite o número desejado. O valor é atualizado automaticamente conforme a faixa.'],['cart','Adicione ao carrinho','Monte um pedido com seguidores, curtidas e visualizações antes de pagar.'],['payment','Pague via PIX','Uma cobrança pode reunir todos os itens do carrinho.'],['order','Acompanhe o pedido','Guarde o código e acompanhe o progresso de cada item.']] as const;
type Step=typeof steps[number][0];
export function PurchaseTutorial({source='home',initialStep,onClose}:{source?:string;initialStep?:Step;onClose:()=>void}){
 const initial=Math.max(0,steps.findIndex(s=>s[0]===initialStep));const[index,setIndex]=useState(initial);const step=steps[index];
 useEffect(()=>{window.dispatchEvent(new CustomEvent('impulsetap-analytics',{detail:{event:'tutorial_opened',source}}));return()=>{window.dispatchEvent(new CustomEvent('impulsetap-analytics',{detail:{event:'tutorial_closed',source}}))}},[source]);
 function finish(){window.dispatchEvent(new CustomEvent('impulsetap-analytics',{detail:{event:'tutorial_completed',source}}));onClose()}
 return <div className="tutorial-backdrop"><section className="tutorial-modal" role="dialog" aria-modal="true" aria-label="Tutorial de compra"><button className="icon-button tutorial-close" onClick={onClose} aria-label="Fechar tutorial"><X/></button><div className="tutorial-progress"><span>Etapa {index+1} de {steps.length}</span><div><i style={{width:`${((index+1)/steps.length)*100}%`}}/></div></div><div className="tutorial-content"><div className="tutorial-illustration"><span>0{index+1}</span><CheckCircle2 size={42}/></div><h2>{step[1]}</h2><p>{step[2]}</p>{step[0]==='quantity'&&<div className="tutorial-example">− <b>2.300</b> +<small>Valor calculado automaticamente</small></div>}{step[0]==='cart'&&<div className="tutorial-example">+ Seguidores · + Curtidas · + Views</div>}</div><div className="tutorial-actions"><button className="button secondary" onClick={()=>index?setIndex(index-1):onClose()}>{index?<><ChevronLeft size={17}/>Voltar</>:'Fechar'}</button>{index<steps.length-1?<button className="button primary" onClick={()=>setIndex(index+1)}>Próxima<ChevronRight size={17}/></button>:<button className="button primary" onClick={finish}>Entendi, quero comprar</button>}</div></section></div>
}
