'use client';
import {useState,type CSSProperties} from 'react';
import Image from 'next/image';
import Link from 'next/link';
import {Check,ChevronDown,ChevronRight,Globe2,Heart,Eye,Bookmark,Share2,Users,MessageCircle,Music2,Clock3,ShieldCheck,LockKeyhole,PackageCheck,Plus,Trash2,MousePointer2,Link2,CreditCard,ReceiptText,SlidersHorizontal,Info} from 'lucide-react';
import {money,number,faqs,type NetworkId,type Service,type Catalog,priceForQuantity,serviceTiers} from '@/lib/catalog';
import {validateLinks,type TargetLink} from '@/lib/validation';
import {settings} from '@/lib/settings';
import {NetworkIcon} from './brand';
import {TrustBar} from './chrome';
import {Checkout} from './checkout';
import {HomeVSL} from './home-vsl';
import {PurchaseTutorial} from './purchase-tutorial';
import {QuantitySelector} from './quantity-selector';
import {addCart,readCart,type CartItem} from '@/lib/cart';
const categoryIcons:Record<string,typeof Users>={'Seguidores':Users,'Inscritos':Users,'Curtidas':Heart,'Visualizações':Eye,'Stories':Eye,'Salvos':Bookmark,'Compartilhamentos':Share2,'Comentários':MessageCircle,'Streams':Music2,'Horas de exibição':Clock3};
export default function Storefront({catalog}:{catalog:Catalog}){
const {networks,services}=catalog;const initial=services.find(s=>s.id==='svc-002')??services[0];
const[networkId,setNetworkId]=useState<NetworkId>(initial.network);const[serviceId,setServiceId]=useState(initial.id);const[packageIndex,setPackageIndex]=useState(0);const[target,setTarget]=useState('');const[multi,setMulti]=useState(false);const[links,setLinks]=useState<TargetLink[]>([{url:'',quantity:500},{url:'',quantity:500}]);const[error,setError]=useState('');const[checkout,setCheckout]=useState(false);const[quantity,setQuantity]=useState(initial.packages[0]?.quantity??1000);const[tutorial,setTutorial]=useState<{step?:'link'|'quantity';source:string}|null>(null);const[cartCount,setCartCount]=useState(0);const[toast,setToast]=useState('');
const network=networks.find(n=>n.id===networkId)!;const networkServices=services.filter(s=>s.network===networkId);const service=networkServices.find(s=>s.id===serviceId)??networkServices[0];const pkg=service.packages[packageIndex]??service.packages[0];const pricing=priceForQuantity(service,quantity)??{tier:serviceTiers(service)[0],total:pkg?.price??0};const selectedPackage={...pkg,quantity,price:pricing.total};const categories=[...new Set(networkServices.map(s=>s.category))];const variants=networkServices.filter(s=>s.category===service.category);
function selectService(s:Service){setServiceId(s.id);setPackageIndex(0);setQuantity(s.packages[0]?.quantity??s.min??100);setTarget('');setMulti(false);setError('')}
function selectNetwork(id:NetworkId){setNetworkId(id);selectService(services.find(s=>s.network===id)!)}
function choosePackage(i:number){setPackageIndex(i);setQuantity(service.packages[i].quantity);setError('');if(multi)setLinks(current=>current.map((l,index)=>({...l,quantity:index===0?service.packages[i].quantity:0})))}
function toggleMulti(checked:boolean){setMulti(checked);setError('');if(checked)setLinks([{url:target,quantity:Math.floor(pkg.quantity/2)},{url:'',quantity:pkg.quantity-Math.floor(pkg.quantity/2)}])}
function startCheckout(){const values=multi?links:[{url:target,quantity}];const err=validateLinks(values,service,quantity,multi);if(err){setError(err);document.getElementById(multi?'multi-link-0':'target-input')?.focus();return;}setError('');setCheckout(true)}
function addToCart(){const values=multi?links:[{url:target,quantity}];const err=validateLinks(values,service,quantity,multi);if(err){setError(err);return;}const item:CartItem={id:crypto.randomUUID(),network:service.network,serviceId:service.id,serviceName:service.name,unit:service.unit,quantity,target:values.map(v=>v.url).join(' · '),price:pricing.total,tierId:pricing.tier.id,unitSize:pricing.tier.unitSize,unitPrice:pricing.tier.pricePerUnit};addCart(item);setCartCount(readCart().length);setToast('Adicionado ao carrinho');setTimeout(()=>setToast(''),2400)}
function selectFeatured(s:Service){setNetworkId(s.network);selectService(s);document.getElementById('servicos')?.scrollIntoView({behavior:'smooth'})}
return <><section className="hero"><div className="container hero-inner"><div className="hero-copy"><div className="hero-label"><span/>Seu próximo passo nas redes</div><h1>Impulsione sua presença <span>nas redes sociais.</span></h1><p>Seguidores, curtidas, visualizações e outros serviços digitais. Escolha o que faz sentido para você, em poucos cliques.</p><div className="hero-actions"><a href="#servicos" className="button primary">Ver serviços</a><Link href="/pedidos" className="button secondary">Acompanhar pedido</Link></div><TrustBar/></div><div className="hero-art"><Image src="/hero.webp" alt="Smartphone com monograma luminoso e ícones de redes sociais" width={1200} height={900} priority/><div className="hero-art-caption"><ShieldCheck size={18}/><span>Seu perfil continua com você.<strong>Nunca pedimos sua senha.</strong></span></div></div></div></section>
<section className="container catalog-section" id="servicos">{catalog.source==='demo'&&<p className="catalog-source-note">Catálogo de demonstração · Conexão com o banco pendente.</p>}<div className="section-heading"><div><span className="section-kicker">Um toque. Várias possibilidades.</span><h2>Qual é o seu próximo movimento?</h2><p>Escolha a rede e monte seu pedido.</p></div><span className="section-detail"><SlidersHorizontal size={16}/>Você no controle</span></div><div className="network-grid" role="group" aria-label="Escolha sua rede social">{networks.filter(n=>n.id!=='google').map(n=><button key={n.id} className={`network-card ${networkId===n.id?'selected':''}`} style={{'--network-color':n.color} as CSSProperties} onClick={()=>selectNetwork(n.id)} aria-pressed={networkId===n.id}><NetworkIcon id={n.id}/><strong>{n.name}</strong><span>{n.description}</span>{networkId===n.id&&<Check className="network-check" size={12}/>}</button>)}</div>
<div className="purchase-layout"><div className="catalog-panel"><div className="catalog-top"><div className="network-title"><NetworkIcon id={networkId}/><div><h3>{network.name}</h3><p>Seu pedido começa aqui.</p></div></div><div className="flow-step"><span>1</span>Escolha seu serviço</div></div><div className="catalog-body"><div className="service-tabs" role="group" aria-label="Tipo de serviço">{categories.map(c=>{const Icon=categoryIcons[c]??Globe2;return <button key={c} className={service.category===c?'active':''} onClick={()=>selectService(networkServices.find(s=>s.category===c)!)} aria-pressed={service.category===c}><Icon size={19}/><span>{c}</span><ChevronRight size={14}/></button>})}</div><div className="service-options"><div className="variant-row">{variants.map(s=><button className={`variant ${s.id===service.id?'selected':''}`} key={s.id} onClick={()=>selectService(s)} aria-pressed={s.id===service.id}><Globe2 size={19}/><span><strong>{s.name}</strong><small>{s.name.includes('brasileir')?'Opção Brasil':s.name.includes('mundia')?'Opção mundial':network.name}</small></span><span className="radio-dot"/></button>)}</div><div className={`package-grid ${service.packages.length===1?'single':''}`}>{service.packages.map((p,i)=><button key={p.id} className={`package-card ${pkg.id===p.id?'selected':''}`} onClick={()=>choosePackage(i)} aria-pressed={pkg.id===p.id}>{p.badge?<span className="package-tag">{p.badge}</span>:i===service.packages.length-1&&i>0&&p.price/p.quantity===Math.min(...service.packages.map(x=>x.price/x.quantity))?<span className="package-tag">Menor preço por mil</span>:null}<span className="package-quantity">{number(p.quantity)}</span><span className="package-unit">{service.unit}</span><strong className="package-price">{money(p.price)}{service.recurring&&<small>/mês</small>}</strong>{p.quantity>=1000&&<span className="unit-price">{money(Math.round(p.price/p.quantity*1000))} por mil</span>}<div className="package-features"><span><Check size={14}/>Sem compartilhar senha</span><span><Check size={14}/>Resumo antes de pagar</span><span><Check size={14}/>Acompanhe seu pedido</span></div><span className={`package-select ${pkg.id===p.id?'active':''}`}>{pkg.id===p.id?<><Check size={15}/>Selecionado</>:'Selecionar'}</span></button>)}</div><p className="service-note"><Info size={15}/>{service.description}</p>{(service.refill||service.delivery)&&<p className="service-note">{service.delivery&&`Prazo: ${service.delivery}. `}{service.refill&&`Reposição: ${service.refill}.`}</p>}<div className="catalog-trust"><span><LockKeyhole size={17}/>Sem senha</span><span><ReceiptText size={17}/>Preço transparente</span><span><PackageCheck size={17}/>Acompanhamento</span></div></div></div></div>
<aside className="checkout-summary" aria-label="Resumo do pedido"><div className="summary-heading"><h3>Seu pedido</h3><span className="summary-step">Passo 2 de 4</span></div><div className="summary-product"><NetworkIcon id={networkId} small/><div><strong>{network.name}</strong><span>{service.name}</span></div></div><div className="summary-lines"><div><span>Quantidade</span><strong>{number(pkg.quantity)} {service.unit}</strong></div><div><span>Valor do pacote</span><strong>{money(pkg.price)}</strong></div></div><div className="total-row"><span>Total{service.recurring?' mensal':''}</span><b>{money(pkg.price)}</b></div><label htmlFor="target-input">{service.targetType==='profile'?'@perfil ou link do perfil':service.targetType==='business'?'Link do Perfil da Empresa':service.targetType==='channel'?'Link público do canal':service.targetType==='track'?'Link da música ou perfil':'Link da publicação ou vídeo'}</label>{!multi&&<input id="target-input" value={target} onChange={e=>{setTarget(e.target.value);setError('')}} placeholder={service.targetType==='profile'?'@seuusuario ou https://…':'https://…'} aria-invalid={!!error} aria-describedby="target-help target-error" maxLength={2048}/>}
{service.multiLink&&settings.enableMultiLink&&<label className="switch-line"><input type="checkbox" checked={multi} onChange={e=>toggleMulti(e.target.checked)}/><span className="switch"/><span>Dividir entre publicações<small>De 2 a 10 links</small></span></label>}
{multi&&<div className="multi-links">{links.map((l,i)=><div className="multi-link" key={i}><label htmlFor={`multi-link-${i}`}>Publicação {i+1}</label><input id={`multi-link-${i}`} value={l.url} placeholder="https://…" onChange={e=>setLinks(links.map((x,j)=>i===j?{...x,url:e.target.value}:x))}/><div><label htmlFor={`qty-${i}`}>Quantidade</label><input id={`qty-${i}`} type="number" min={1} max={pkg.quantity} step={1} value={l.quantity} onChange={e=>setLinks(links.map((x,j)=>i===j?{...x,quantity:Number(e.target.value)}:x))}/><button className="icon-button" disabled={links.length<=2} aria-label={`Remover publicação ${i+1}`} onClick={()=>setLinks(links.filter((_,j)=>j!==i))}><Trash2 size={16}/></button></div></div>)}<div className="distribution-total">Distribuído: {number(links.reduce((sum,l)=>sum+l.quantity,0))} / {number(pkg.quantity)}</div><button className="button secondary full" disabled={links.length>=10} onClick={()=>setLinks([...links,{url:'',quantity:0}])}><Plus size={16}/>Adicionar link</button></div>}
<p id="target-help" className="input-help"><LockKeyhole size={12}/>Não solicitamos sua senha.</p>{error&&<p className="error" role="alert" id="target-error">{error}</p>}<button className="button primary full" onClick={startCheckout}>Continuar</button><p className="summary-footnote">Dados e pagamento na próxima etapa</p></aside></div>
</section>
<section className="container featured-section"><div className="section-heading small"><div><h2>Mais possibilidades para explorar</h2><p>Encontre o serviço que combina com seu objetivo.</p></div></div><div className="featured-grid">{['svc-002','svc-013','svc-019','svc-025','svc-053','svc-045'].map(id=>services.find(s=>s.id===id)).filter((s):s is Service=>Boolean(s)).map(s=>{const id=s.id;return <button className="featured-card" key={id} onClick={()=>selectFeatured(s)}><span className="featured-network"><NetworkIcon id={s.network} small/>{networks.find(n=>n.id===s.network)?.name}</span><strong>{s.name}</strong><span className="muted">{number(s.packages[0].quantity)} {s.unit}</span><b>{money(s.packages[0].price)}</b><span className="featured-cta">Ver opções <ChevronRight size={14}/></span></button>})}</div></section>
<section className="container google-section"><div className="google-intro"><NetworkIcon id="google"/><div><h2>Sua reputação começa com experiências reais.</h2><p>Perfil da Empresa, avaliações autênticas e gestão profissional no Google.</p></div><span className="real-tag"><ShieldCheck size={15}/>Somente avaliações reais</span></div><div className="google-grid">{services.filter(s=>s.network==='google').map(s=><button key={s.id} onClick={()=>selectFeatured(s)}><strong>{s.name}</strong><span>{money(s.packages[0].price)}{s.recurring?'/mês':''}</span><span className="google-link">Conhecer serviço <ChevronRight size={14}/></span></button>)}</div></section>
<section className="container how-section" id="como-funciona"><div className="section-heading"><div><span className="section-kicker">Simples do início ao fim</span><h2>Seu pedido, sem complicação.</h2></div><p>Você escolhe. Você acompanha.</p></div><div className="how-grid">{[[MousePointer2,'Escolha seu serviço','Selecione a rede e o pacote ideal.'],[Link2,'Informe o link','Seu perfil ou publicação. Nunca sua senha.'],[CreditCard,'Revise e pague','Confira todos os detalhes antes de finalizar.'],[ReceiptText,'Acompanhe o pedido','Consulte cada etapa em Meus pedidos.']].map(([Icon,title,desc],i)=>{const I=Icon as typeof MousePointer2;return <div className="how-card" key={String(title)}><div className="how-top"><I size={24}/><span>0{i+1}</span></div><h3>{String(title)}</h3><p>{String(desc)}</p></div>})}</div></section>
<section className="container faq-section" id="duvidas"><div className="faq-intro"><span className="section-kicker">Tudo às claras</span><h2>Alguma dúvida?<br/>Vamos simplificar.</h2><p>As informações que você precisa para escolher com tranquilidade.</p><div className="faq-trust"><ShieldCheck size={30}/><div><strong>Transparência em cada toque.</strong><p>Sem promessas de vendas ou monetização garantida.</p></div></div></div><div className="faq-list">{faqs.map(([q,a])=><details key={q}><summary>{q}<ChevronDown size={18}/></summary><p>{a}</p></details>)}</div></section><section className="container closing"><div><span className="section-kicker">Sua presença. Seu próximo passo.</span><h2>Vamos colocar seu perfil<br/>em movimento?</h2></div><a href="#servicos" className="button primary">Escolher meu serviço</a></section>
{checkout&&<Checkout catalog={catalog} service={service} pkg={pkg} links={multi?links:[{url:target,quantity:pkg.quantity}]} onClose={()=>setCheckout(false)}/>}</>
}
